version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_USER=jahongirhodjaniyazov
      - POSTGRES_PASSWORD=745296rar
      - POSTGRES_DB=pixigramprod
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: unless-stopped
    
  server:
    build: 
      context: .
      dockerfile: server/Dockerfile 
    container_name: pixigram_server
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
    restart: unless-stopped
    