version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_USER=pixigram
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=pixigramprod
    env_file:
      - .env
    restart: unless-stopped
  
  frontend: 
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pixigram_client
    ports:
      - "8080:8080"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: 
      context: .
      dockerfile: server/Dockerfile 
    container_name: pixigram_server
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:8.0-rc1-alpine

    